$('.PassUpdateWord').html('Changing password...');BlurUno=function(){$(".InputUnoDiv").removeClass("t");if($('.InputUno').val()){$(".InputUnoDiv").removeClass("wb").addClass('Wb')}
else{$(".InputUnoDiv").removeClass("Wb").addClass('wb')}
processvalidate()};BlurDos=function(){$(".InputDosDiv").removeClass("t");if($('.InputDos').val()){$(".InputDosDiv").removeClass("wb").addClass('Wb')}
else{$(".InputDosDiv").removeClass("Wb").addClass('wb')}};$('[data-action="CloseUpdateInfo"]').on('click',function(){$(".Na .a-aa").removeClass("DisplayAlways");$(".Na .a-aa").addClass("HideAlways")});ClassTest='text';var Input1Type='password';var Input2Type='password';ShowInput1=!1;ShowInput2=!1;show_pass=function(){if(Input1Type=='password'){$('.InputUno').attr('type','text')}
else{$('.InputUno').attr('type','password')}
Input1Type=$('.InputUno').attr('type');$('.Input1TypeShow').toggle();$('.Input1TypeHide').toggle()};show_pass_conf=function(){if(Input2Type=='password'){$('.InputDos').attr('type','text')}
else{$('.InputDos').attr('type','password')}
Input2Type=$('.InputDos').attr('type');$('.Input2TypeShow').toggle();$('.Input2TypeHide').toggle()};validate=function(){instantscore();keyDown2()};processvalidate=function(){$('[data-name="valprocess"]').html(null);var password=$('.InputUno').val();if(password){if(password.length>7&&!password.match(/([a-z]|[A-Z]){0,}(?:([0-9]){0,})/)){$('[data-name="valprocess"]').html('Please choose a stronger password. Try a mix of letters, numbers, and symbols.');$('[data-name="validationword"]').html('Weak')}
if(password.length>7&&password.match(/(?:((?:1){2}|(?:2){2}|(?:3){2}|(?:4){2}|(?:5){2}|(?:6){2}|(?:7){2}|(?:8){2}|(?:9){2}|(?:0){2}){3,})|(?:123456789)|(?:987654321)|(123654789)|987456321|147852369|963258741|014789|abc1234/)){$('[data-name="valprocess"]').html('Please choose a stronger password. Try a mix of letters, numbers, and symbols.');$('[data-name="validationword"]').html('Weak')}
if(password.length>100)
{$('[data-name="valprocess"]').html('Must have at most 100 characters.');$('[data-name="validationword"]').html('Weak')}
else if(password.length>7&&!password.match(/([a-zA-Z]+)/)){valprocessgood=!0;$('[data-name="validationword"]').html('Fair')}
else if(password.length>7&&password.match(/.*\W\D.*/)){valprocessgood=!0;$('[data-name="validationword"]').html('Strong')}
else if(password.length>7){valprocessgood=!0;$('[data-name="validationword"]').html('Good')}
else{$('[data-name="valprocess"]').html('Please choose a longer password.');$('[data-name="validationword"]').html('Too Short')}}
else{valprocessgood=!1}
if($('[data-name="valprocess"]').html()){$(".InputUnoDiv").addClass("vb Gj")}
else{$(".InputUnoDiv").removeClass("vb Gj")}};instantscore=function(){valprocessgood=!1;$('[data-name="validationword"]').html('Too Short');var password=$('.InputUno').val();if(password){if(password.length>7&&!password.match(/([a-z]|[A-Z]){0,}(?:([0-9]){0,})/)){$('[data-name="validationword"]').html('Weak')}
else if(password.length>7&&!password.match(/([a-zA-Z]+)/)){$('[data-name="validationword"]').html('Fair')}
else if(password.length>7&&password.match(/.*\W\D.*/)){$('[data-name="validationword"]').html('Strong')}
else if(password.length>7){$('[data-name="validationword"]').html('Good');valprocessgood=!0}
else{$('[data-name="validationword"]').html('Too Short')}}};keyDown1=function(){if(Stopped1){processvalidate()}};Verify1=function(){valprocessgood=!1;processvalidate();var password=$('.InputUno').val();if(!password||$('[data-name="valprocess"]').html()||!valprocessgood){Stopped1=!0;$(".InputUnoDiv").addClass("vb Gj");instantscore();if(!$('[data-name="valprocess"]').html())$('[data-name="valprocess"]').html('Please choose a longer password.')}};keyDown2=function(){var passwordConfirm=$('.InputDos').val();var password=$('.InputUno').val();if(Stopped2&&passwordConfirm==password){$(".InputDosDiv").removeClass("vb Gj");$('.passwordConfirmerror').html(!1).hide();Stopped2=null;valprocess2good=!0}};Verify2=function(){valprocess2good=!1;var passwordConfirm=$('.InputDos').val();var password=$('.InputUno').val();if(password&&password!=passwordConfirm){Stopped2=!0;$(".InputDosDiv").addClass("vb Gj");$('.passwordConfirmerror').html('Passwords don\'t match.').show();valprocess2good=!1}
else if(password==passwordConfirm)valprocess2good=!0};ChangePassword=function(){var password=$('.InputUno').val();if(password==OldPass)
{$('[data-name="valprocess"]').html('You used this password recently. Please choose a different one.');$('[data-name="validationword"]').html('Weak');return!1}
$(".O.Ya.rb.pa").addClass("m");setTimeout(function(){$(".O.Ya.rb.pa").removeClass("m")},300);Verify1();Verify2();if(valprocessgood&&valprocess2good){$(".Na .a-aa").addClass("DisplayAlways");$(".Na .a-aa").removeClass("HideAlways");setTimeout(function(){$('.PassUpdateWord').html('Your password was changed.')},3000);setTimeout(function(){$('#form').submit()},3500);return!0}};Hidelabel=function(){$(".i1").addClass("HideBlockAlways")};PhoneKDown1=function(){if(!PhoneInput1||!PhoneInput2){CompleteForm='disabled'}
else{CompleteForm=null}}
PhoneKDown2=function(){if(!PhoneInput1||!PhoneInput2){CompleteForm='disabled'}
else{CompleteForm=null}}
PhoneDone=function(){$('#form').submit()}
$('.InputUno').focus();$(".InputUnoDiv").addClass("t");$('.InputUno').focus(function(){$(".InputUnoDiv").addClass("t")});$('.InputUno').keydown(function(){$(".InputUnoDiv").addClass("t")});$('.InputDos').focus(function(){$(".InputDosDiv").addClass("t")});$('.InputDos').keydown(function(){$(".InputDosDiv").addClass("t")});var LoginOpen=!1;var OthersOpen=!1;var NotificationsOpen=!1;function ShowGbs(ClassName){$(ClassName+" .gb_ab").addClass("DisplayBlockAlways");$(ClassName+" .gb_bb").addClass("DisplayBlockAlways")}
function HideGbs(ClassName){$(ClassName+" .gb_ab").removeClass("DisplayBlockAlways");$(ClassName+" .gb_bb").removeClass("DisplayBlockAlways")}
function PleaseShowOptions(){$(document).mouseup(function(e){var container=$("#loginPanel");var container2=$(".ShowloginPanel");if((!container.is(e.target)&&container.has(e.target).length===0)&&(!container2.is(e.target)&&container2.has(e.target).length===0)){container.removeClass("DisplayBlockAlways");LoginOpen=!1;HideGbs('.gb_jc.gb_8a.gb_Me.gb_R')}});if(LoginOpen==!1){ShowGbs('.gb_jc.gb_8a.gb_Me.gb_R');$("#loginPanel").addClass("DisplayBlockAlways");LoginOpen=!0;$(".gb_6a.gb_Vc.gb_Me.gb_R").fadeIn(400,function(){$(this).focus()});$("#loginPanel").fadeIn(400,function(){$(this).focus()})}
else{$("#loginPanel").removeClass("DisplayBlockAlways");LoginOpen=!1;HideGbs('.gb_jc.gb_8a.gb_Me.gb_R');return}}
function PleaseShowOther(){$(document).mouseup(function(e){var container=$("#OthersPanel");var container2=$(".ShowOther");if((!container.is(e.target)&&container.has(e.target).length===0)&&(!container2.is(e.target)&&container2.has(e.target).length===0)){container.removeClass("DisplayBlockAlways");OthersOpen=!1;HideGbs('.gb_ea.gb_Vc.gb_R')}});if(OthersOpen==!1){ShowGbs('.gb_ea.gb_Vc.gb_R');$("#OthersPanel").addClass("DisplayBlockAlways");OthersOpen=!0;return}
else{OthersOpen=!1;$("#OthersPanel").removeClass("DisplayBlockAlways");HideGbs('.gb_ea.gb_Vc.gb_R');return}}
function PleaseShowNotifications(){$(document).mouseup(function(e){var container=$("#NotificationsPanel");var container2=$(".ShowNotificationsPanel");if((!container.is(e.target)&&container.has(e.target).length===0)&&(!container2.is(e.target)&&container2.has(e.target).length===0)){container.removeClass("DisplayBlockAlways");NotificationsOpen=!1;HideGbs('.gb_gc.gb_Vc.gb_R.gb_hc')}});if(NotificationsOpen==!1){ShowGbs('.gb_gc.gb_Vc.gb_R.gb_hc');$("#NotificationsPanel").addClass("DisplayBlockAlways");NotificationsOpen=!0;setTimeout(function(){$(".Frame1").addClass("HideAlways").removeClass("DisplayAlways");$(".Frame2").addClass("DisplayAlways").removeClass("HideAlways")},1300);return}
else{$("#NotificationsPanel").removeClass("DisplayBlockAlways");NotificationsOpen=!1;HideGbs('.gb_gc.gb_Vc.gb_R.gb_hc');return}}